In [1]:
# Numpy Array 
# Need to import numpy using "import numpy"

In [2]:
import numpy as np

In [3]:
# Creating an array
a= np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
# Creating an array with string and integer
a=np.array(["abc",1,2,3,"bcd"])
print(a)

['abc' '1' '2' '3' 'bcd']


In [6]:
#Creating a complex in array
a=np.array([1,2,3],dtype=complex) # dtype is used to create the complex variable
print(a)

a= np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) # dtype is used to create the complex variable
print(a)

[1.+0.j 2.+0.j 3.+0.j]
[(1, 2) (3, 4)]


In [7]:
# Creating a 3 dimensional array
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
# Creating an array from list
lst=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(lst)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
