In [13]:
import numpy as np
from numpy import random as rd

In [14]:
# Sorting

In [15]:
# Sorting the numbers
a= rd.randint(1,100,30) # Creating a 30 elements between the numbers 1 to 100
b=np.sort(a) # Sorting the element of a using sort()
print(b)

[ 2  4  8 11 20 20 25 26 30 31 34 35 37 45 48 48 52 53 55 56 63 63 64 67
 72 85 88 90 94 97]


In [16]:
# Creating a matrix from the sorted numbers
c=b.reshape(6,5) #  creating a 6X5 matrix from 30 elements
print(c)

[[ 2  4  8 11 20]
 [20 25 26 30 31]
 [34 35 37 45 48]
 [48 52 53 55 56]
 [63 63 64 67 72]
 [85 88 90 94 97]]


In [17]:
print(c.argmax(axis=1)) # Index of the maximum element in a column

[4 4 4 4 4 4]


In [18]:
print(c.argmax(axis=0)) # Index of the maximum element in a row

[5 5 5 5 5]


In [19]:
print(c.max()) # Maximum element in a matrix
print(c.min()) # Minimum element in a matrix

97
2


In [23]:
# Subsetting
a=rd.randint(1,50,30).reshape(6,5)
print(a)

[[40 15 28  2 15]
 [19 41 30 46 31]
 [30  9  4 30 36]
 [13 40 19 29 38]
 [ 9 42 16 20 37]
 [40 12 12 43 33]]


In [22]:
print(a>25) # Print True or False for the numbers present in the matrix greater than 25

[[ True  True False False False]
 [ True  True False False  True]
 [ True  True  True  True  True]
 [False  True False False False]
 [False False  True False False]
 [False False  True False  True]]
[35 33 45 40 45 38 29 41 32 33 31 27 43 33]


In [24]:
print(a[a>25]) # Print the numbers present in the matrix greater than 25.
               # This is called Subsetting

[40 28 41 30 46 31 30 30 36 40 29 38 42 37 40 43 33]
